### ISSUE TITLE
Burnup charts

### ISSUE THREAD

**Issue by santiagoworkana** [plan4hub/yoda#1]
> partof plan4hub/yoda-demo#155 *Linking to org issues - testing*

> contains (total estimate: 0, total remaining: 0, # open issues: 1, # closed issues: 0)
- [ ] #12 *test*

It would be a nice addition to have a burnup chart which can also show the acumulated backlog to make a comparision.
http://blog.plataformatec.com.br/2016/02/why-we-love-metrics-throughput-and-burnup-charts/ in this article it explain well the benefits.

**Comment by jens-markussen** [comment]
Ok, reviewed the first part, namely the suggested "Throughtput chart". Basicly, this chart looks at the issues closed per time period (e.g. per week) and plots that vs. the backlog of issues. 

This is very similar to the Time Statistics graph already supported by Yoda. Here you may ask to show closed issues over time. However, the default is to show on the right axis the total of closed issues across whatever bars you have chosen to split issues into. 

[Example - as before](https://hewlettpackard.github.io/yoda/yoda-time-stats.html?owner=hewlettpackard&repolist=yoda-demo&labelfilter=T2%20-%20Enhancement&count=closed&draw=true)

What I've done, is to add a checkbox that allows the right axis to show instead the # of open issues (the issues backlog) at that time. This then produced a Throughput graph.

[Example - with new "Right total" checkbox checked](https://hewlettpackard.github.io/yoda/yoda-time-stats.html?owner=hewlettpackard&repolist=yoda-demo&labelfilter=T2%20-%20Enhancement&count=closed&righttotal=true&draw=true)

Remember that you can of course filter issues, e.g. to show only Enhancements/changes/user stories as opposed to Defects/bugs.

Next step, I'll look at Burnup charts, which look a bit more elaborate... watch this space.

**Comment by santiagoworkana** [comment]
Wow! awsome! thanks!! i'll keep looking at it and if I have some more suggestiong i'll add other issue! :)
