### ISSUE TITLE
Yoda seems to have disappeared? I'm getting a 404 when I try to use it

### ISSUE THREAD

**Issue by DrLoebl** [plan4hub/yoda#26]
![image](https://github.com/plan4hub/yoda/assets/42491601/fb12583d-7832-4ebe-9c80-a6dcf9d0f7a4)

**Comment by DrLoebl** [comment]
tagging @jens-markussen - hopefully you can fix it or let me know what's happened.

**Comment by jens-markussen** [comment]
Hi. Yoda is moving, and the move was perhaps done a bit sudden. Sorry about that.

Now avaialble at https://plan4hub.github.io/yoda/

I will be updating further links, descriptions, etc.

**Comment by DrLoebl** [comment]
Ah, thanks for the prompt response!

**Comment by jens-markussen** [comment]
Welcome

**Comment by DrLoebl** [comment]
Do I need to redo the setup, or can I just use the new URL?

**Comment by DrLoebl** [comment]
Looks like I do
